scenario.description = Receiver test - exception in sub-adapter - message in error store
			   
include = ../../common.properties

manage.dbwrapper.param1.name=expectedNumberOfResults
manage.dbwrapper.param1.value=1
manage.dbwrapper.param2.name=numberOfAttempts
manage.dbwrapper.param2.value=30

# clear IbisTemp and IbisStore
step1.manage.db.write = common/md-delete.xml
step2.manage.db.read  = ../../common/md-delete-result.xml

#insert a record
step3.manage.db.write = common/md-insert.xml
step4.manage.db.read  = ../../common/md-insert-result.xml

step6.java.callback.read = ignore
step5.java.callback.writeline = <root forward="java-sender" child-forward="exception" />
# message is retried and thus this sender is called again.
step7.java.callback.read = ignore

step8.manage.dbwrapper.write = common/md-wait-till-message-in-errorstorage.xml
step9.manage.dbwrapper.read = ignore

step10.manage.db.write = common/md-select.xml
step11.manage.db.read = ../common/result-error-retried-twice-and-in-error.xml
